### ISSUE TITLE
AGS Validator Does not Pick up Inconsistent Types across the same columns in different groups

### ISSUE THREAD

**Issue by MatteMatto** [BritishGeologicalSurvey/pyagsapi#148]
We use Openground for our geotechnical database, one of the issues we are having is files from one of our suppliers pass through the validator, but are not accepted by Openground.

The issue is as follows:
Where the same column e.g ISPT_HMSP, is used in multiple groups inside the AGS file, the ags file can have different types or units specified in those different groups. such that the type is specified as X in one place and something else in another group for the same column. Can this be added to the validator please?

Cheers

Matt

**Comment by KoalaGeo** [comment]
@MatteMatto  I believe this issue relates to the underlying ags python library (https://gitlab.com/ags-data-format-wg/ags-python-library) not the BGS implementation.

**Comment by KoalaGeo** [comment]
However...

The validator enforces the rules. If user-defined fields are used and they abide by the rules then they pass the validator.

In this instance, I suggest that the receiver of the data asks the issuer why they have specified a user-defined field that has different data types in different groups and ask them to change it.

The issue you raise though could be included in the validator as a warning / fyi although it didn't break the ags rules.

**Comment by KoalaGeo** [comment]
Closing as raised on GitLab
