### ISSUE TITLE
Validate data integrity

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/pyagsapi#21]
### Summary

We would like to validate data integrity so that we can find data errors as well as formatting errors.

### Description

BGS data ingestion procedures check the data before a file is imported.
Many of these checks are generic and also useful outside of BGS.
This ticket describes the checks that should be implemented in this project.
There will be separate discussion as to how the checks will be wired up to the API.

#### Formatting

+ [x] Number of columns must match number of column headers
+ [x] Groups must include PROJ, LOCA or HOLE, ABBR, TYPE, UNITS
+ [x] DICT is required if any user defined groups or headings are present. 
  - covered in rule 9 & rule 18
+ [x] For any table that has a LOCA_ID column, the LOCA_ID should exist in the LOCA table
+ [x] In LOCA - TYPE for LOCA_NATE/NATN/LOCX/LOCY should be 2DP

#### Coordinates

+ [x] Spatial referencing system or projection format should be specified in LOCA_GREF, LOCA_LREF or LOCA_LLZ columns 
+ [x] Eastings and northings which are not zero or null
+ [x] OSGB Eastings and northings lie with normal range (100000 < Easting < 800000, 100000 < Northing < 1400000) in LOCA_NATE and LOCA_NATN columns
+ [ ] LAT/LON coordinates should be in the LOCA_LAT and LOCA_LON columns(or HOLE equivalent)
+ [x] LOCA_LOCX and LOCA_LOCY column cords if present should not duplicate LOCA_LAT/LONG or LOCA_NATE/NATN 
+ [x] Identification and validation of Irish National Grid coordinates in LOCA_NATE/N
+ [x] Drill depth is not null or zero
+ [x] Drill depth has no corresponding record in GEOL group
+ [x] Coordinates lie within GB boundary polygon (this is only be useful for GB-specific validation)

### Acceptance criteria

+ [x] Function(s) created that can take ~an `.ags` file~ a `tables` dictionary of numeric dataframes and report pass/fail for each of those tests

**Comment by andy-bevan** [comment]
I have some python code somewhere which carries out these checks - I'll dig it out in case its useful.

**Comment by andy-bevan** [comment]
> I have some python code somewhere which carries out these checks - I'll dig it out in case its useful.

[ConvertAGStoSQLite_v4.txt](https://github.com/BritishGeologicalSurvey/AGS-Validator/files/7022201/ConvertAGStoSQLite_v4.txt)

**Comment by KoalaGeo** [comment]
Same as Issue #14

**Comment by KoalaGeo** [comment]
LOCA_NATE/N sometimes contain Irish Grid co-ords which is correct, but it will fail stage2 validation (inside UK+NI Boundary check) - In stage 2 validation these are copied to new columns and the OSGB co-ords are regenerated and inserted where possible (SW Ireland isn’t covered otherwise Lat/Long generated)

**Comment by KoalaGeo** [comment]
![image](https://user-images.githubusercontent.com/33657876/130823911-3ed02c21-bb2c-49d5-9fd2-974db7ca86bb.png)

**Comment by KoalaGeo** [comment]
![image](https://user-images.githubusercontent.com/33657876/130823983-c9ef4f40-2fbb-4164-a478-c468832c6f85.png)

**Comment by KoalaGeo** [comment]
Closing issue asall main points addressed. Will raise separate issue re lat/long validation.
