### ISSUE TITLE
Referential Integrity - SAMP Group

### ISSUE THREAD

**Issue by andy-bevan** [BritishGeologicalSurvey/pyagsapi#22]
If we are validating against rules 10a, 10b and 10c then this should mostly be covered but there are some peculiarities around the identification of SAMP records in the section titled ‘Sample Referencing’ in note iv. 

I was wondering if we could validate that either:

* SAMP_ID is populated and unique within the SAMP group

Or

* LOCA_ID, SAMP_TOP, SAMP_TYPE, SAMP_REF are all populated, not null,  and unique in combination within SAMP group 
AND all LOCA_ID values are present in the LOCA group

Also

* All groups that reference the SAMP group as a parent, use either the SAMP_ID field or the combination of LOCA_ID, SAMP_TOP, SAMP_TYPE, SAMP_REF and that the parent exists in the SAMP group.

**Comment by volcan01010** [comment]
Ways to fail:

+ SAMP_ID is missing
+ SAMP_ID has duplicates
+ SAMP_ID not referenced in children

or if no SAMP_ID

+ composite is missing
+ composite has duplicates
+ composite LOCA_ID isn't in LOCA group
+ composite not referenced in children

if both

+ SAMP_ID and composite are not always paired

**Comment by andy-bevan** [comment]
I don't think it matters if there is a SAMP record without a child reference. 

However, a child record without a matching SAMP parent does matter.

**Comment by ximenesuk** [comment]
@andy-bevan Thanks for that clarification. That's what we understood but didn't phrase well above.

Is there a situation where sample data will have a mix of valid `SAMP_ID`s and composite IDs using the four other columns within one file? So as below one row has a `SAMP_ID` and the other does not but does have the other four fields?
```
GROUP","SAMP"
"HEADING","LOCA_ID","SAMP_TOP","SAMP_REF","SAMP_TYPE","SAMP_ID",...
...
"DATA","327-16B","24.55","24","U","A12345",...
"DATA","327-16A","24.55","24","U","",...
```

**Comment by andy-bevan** [comment]
I'll build a query to see if there are any existing cases...

**Comment by andy-bevan** [comment]
I'm afraid I found quite a few examples where that occurs, yes.

E.g.

BH04B	11	32	D	\\kwsan\Store\DDS\AGS_Validation_Stage2\AGS_CSV_Archive\128125\HE Report 30382.ags	
BH04B	11	32	D	\\kwsan\Store\DDS\AGS_Validation_Stage2\AGS_CSV_Archive\128125\HE Report 30382.ags	GEL_20180319111

**Comment by ximenesuk** [comment]
Thanks! I just wanted to check before building the logic.

**Comment by KoalaGeo** [comment]
Fixed in https://github.com/BritishGeologicalSurvey/pyagsapi/pull/47
