### ISSUE TITLE
Fixes and issues for upstream ags-python-library

### ISSUE THREAD

**Issue by volcan01010** [BritishGeologicalSurvey/pyagsapi#24]
### Summary

As we use the ags-python-library we want to report/fix problems so that it can be improved for us and others.

### Details

Issues/ Fixes / merge requests to make:

+ [x] Make pull request on `ags4_cli` to in original code to return non-zero exit code on Error
+ [ ] Make pull request on `ags4_cli` to make sure Metadata is included in error logs
+ [x] `ags4_cli convert` will create a garbage .xlsx file from a garbage .ags file
  - https://gitlab.com/ags-data-format-wg/ags-python-library/-/issues/21
+ [x] Remove requests for user input eg  asking if user wants to rename duplicates headings.
  - https://gitlab.com/ags-data-format-wg/ags-python-library/-/issues/22

From #30 

+ [x] Fix UnboundLocalError bug in upstream repo
+ [x] Report/fix sys.exit() calls in upstream library

**Comment by KoalaGeo** [comment]
Some files popsa prompt asking if user wants to rename duplicates.  

In the command line tool could tell the system to respond with "n", but not sure how to do that directly in the library.

**Comment by volcan01010** [comment]
This merge request updates the CLI to provide exit codes and extends the upstream fix for not asking about renaming duplicate headers. https://gitlab.com/ags-data-format-wg/ags-python-library/-/issues/22#note_684506706

**Comment by KoalaGeo** [comment]
Complete
