### ISSUE TITLE
Map in HTML data validation response

### ISSUE THREAD

**Issue by KoalaGeo** [BritishGeologicalSurvey/pyagsapi#32]
Accessions and Users should be able to verify LOCA table on a map. 

Options:

1. Add function to validate endpoint
2. Add new dedicated endpoint

Input: 1+ .ags files

Function: .ags > pandas > export geojson from loca using LAT / LONG - if not present, OSGB converted to LAT/LONG. May need epsg code input parameter. 

Output: GeoJSON + HTML (Leaflet/Openlayers with GeoJSON features) or PNG static map - maybe use https://github.com/flopp/py-staticmaps / https://github.com/pamelafox/staticmaps-function

**Comment by KoalaGeo** [comment]
Best way to implement?

/locate/ endpoint to extract (& transform OSGB to WGS84 if not present) and return geojson

Front end data validation form calls both /validatedatamany/ and /locate/ to validate and return leaflet map of hole locations?

**Comment by KoalaGeo** [comment]
Low Priority, but would be nice to have

**Comment by volcan01010** [comment]
Notes from Edd chat:

+ Check LOCA_GREF for "BNG", "OSGB" or "*27700"
+ Check LOCAL_LLZ is WGS84

We need one point for every entry in the LOCA table, but it should be prefixed by the PROJECT ID in case of duplicates.
