### ISSUE TITLE
internal server error response when doing BGS checks & f=JSON

### ISSUE THREAD

**Issue by KoalaGeo** [BritishGeologicalSurvey/pyagsapi#57]
East West Rail BGS Pre October 2018 upload (partial) .ags

**Comment by KoalaGeo** [comment]
Is it the same error with these 3 - https://github.com/BritishGeologicalSurvey/pyagsapi/wiki/File-Summaries#json-response--internal-server-error-txt-works ??

**Comment by ximenesuk** [comment]
It looks like there is another issue with this file:
```
[2023-02-22 15:17:03 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:7)
[2023-02-22 15:17:03 +0000] [1] [WARNING] Worker with pid 7 was terminated due to signal 6
[2023-02-22 15:17:03 +0000] [10] [INFO] Booting worker with pid: 10
```
It times out and crashes! The file is relatively big,  30 MB, but less than the 50 MB supported. It would be good to islotae the two problems, if there are two.

**Comment by ximenesuk** [comment]
> Is it the same error with these 3 - https://github.com/BritishGeologicalSurvey/pyagsapi/wiki/File-Summaries#json-response--internal-server-error-txt-works ??

These were failing for a different reason which I have now fixed. A bug in the BGS code. I'll use on of those files as a test case.
