### ISSUE TITLE
Add Single Borehole and Spatial Search endpoints to AGS Exporter API

### ISSUE THREAD

**Issue by KoalaGeo** [BritishGeologicalSurvey/pyagsapi#99]
Endpoints for the AGS Exporter API

![image](https://user-images.githubusercontent.com/33657876/231485950-50b1f2cf-f556-4650-87b9-f4c13b59d559.png)

Single Borehole - Proposed Logic:
- Input: {integer} as BGS_LOCA_ID
- POST BGS_LOCA_ID in body to https://gwbv.bgs.ac.uk/ags_export/
- https://gwbv.bgs.ac.uk/ags_export/ will return a .zip containing .ags file(s)

Spatial Input - Proposed Logic:

- Input: {polygon} as Well Known Text
- Query - https://ogcapi.bgs.ac.uk/collections/agsboreholeindex/items?f=json&properties=bgs_loca_id&filter=INTERSECTS%28shape,{polygon}%29&limit=10
- If `numberMatched` = >10 return error "10 Boreholes maximum, choose a smaller area"
- If `numberMatched` = <10
- Extract `bgs_loca_id` from returned geojson
- put in ; delimited list 
- POST in body to https://gwbv.bgs.ac.uk/ags_export/
- https://gwbv.bgs.ac.uk/ags_export/ will return a .zip containing .ags file(s)

Longer term potential move whole java application (https://kwvmxgit.ad.nerc.ac.uk/java-web/uk.ac.bgs.ags.exporter) to python

**Comment by ximenesuk** [comment]
Note that the export is a GET using https://gwbv.bgs.ac.uk/ags_export?loca_ids=20190430093402523419

where https://gwbv.bgs.ac.uk/ags_export?loca_ids=id1:id2:id3 can also be used.
